basePath: /v1
definitions:
  handlers.exchangeTokenBody:
    properties:
      code:
        type: string
    type: object
host: localhost:6969
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Twitch Genie API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Twitch Genie API
  version: "1.0"
paths:
  /exchange-token:
    post:
      description: Exchange the auth token and retrieve user data
      parameters:
      - description: Exchange token body
        in: body
        name: exchangeTokenBody
        required: true
        schema:
          $ref: '#/definitions/handlers.exchangeTokenBody'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Exchange token
      tags:
      - Authentication
  /health:
    get:
      operationId: health
      responses: {}
      summary: check the API health
swagger: "2.0"
